# Generated by Django 4.2.10 on 2024-02-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_ticker_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
