# Generated by Django 4.2.9 on 2024-01-23 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('ticker', 'user')},
        ),
    ]
